/* ****************************************************************************
       This is a TEMPORARY file generated by the Awe Algol W compiler
       from an Algol W source file. You should not edit this file or store it
       in a version control system; delete it freely as you would any other 
       temporary object file. You should NOT distribute this file,
       instead distribute your Algol W source file and the Awe compiler.
   **************************************************************************** */

     
#include <awe.h>
static const char * const _awe_src_0 = "<stdin>";
static const char * const _awe_src_1 = "(Predeclared Identifiers)";
static const char * const _awe_src_2 = "program.alw";


     int _awe_argc;
     char **_awe_argv;
     int main (int argc, char **argv) {
       _awe_argc = argc;
       _awe_argv = argv;
       _awe_init(_awe_at(2,8,0));
       {
void separate (_awe_str message);
{ _awe_Editing_t _editing_state;
                 _awe_Editing_save(&_editing_state);
                 _awe_iocontrol(_awe_at(2,5,3), 2);
_awe_write_string(_awe_at(2,5,3), (_awe_str)"Here we go:", 11);
_awe_Editing_restore(&_editing_state);
               }
              {
unsigned char _separate_arg1[10];
_awe_str_cpy(_separate_arg1, 10, (_awe_str)"Hi there!", 9);
separate(_separate_arg1);
}
{ _awe_Editing_t _editing_state;
                 _awe_Editing_save(&_editing_state);
                 _awe_iocontrol(_awe_at(2,7,3), 2);
_awe_write_string(_awe_at(2,7,3), (_awe_str)"Done.", 5);
_awe_Editing_restore(&_editing_state);
               }
              ; /*empty*/
}
       _awe_finalize(_awe_at(2,8,0));
       return 0;
     }
     
